services:
  - type: web
    name: visit-tracker
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: Visit Tracker
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: error
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/storage/database/database.sqlite
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_DRIVER
        value: file
